# Generated by Django 3.1.3 on 2020-11-28 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('UF', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Prefeito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.IntegerField()),
                ('partido', models.CharField(max_length=20)),
                ('plano', models.URLField(max_length=400)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.municipio')),
            ],
        ),
    ]
