# Generated by Django 3.1.3 on 2020-11-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201128_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mylist',
            old_name='username',
            new_name='nome',
        ),
    ]
