# Generated by Django 3.1.3 on 2020-12-02 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201130_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='prefeito',
            name='foto',
            field=models.CharField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
    ]
